on: [push, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        sdl: [1, 2]
    env:
      CXX: g++
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y
          cmake
          g++
          libsdl1.2-dev
          libsdl-image1.2-dev
          libsdl-mixer1.2-dev
          libsdl2-dev
          libsdl2-image-dev
          libsdl2-mixer-dev
          libegl1-mesa-dev
          libgles2-mesa-dev
      - run: |
          $CXX --version
          cmake --version
          mkdir build
      - name: Configure
        if: matrix.sdl == 1
        working-directory: build
        run: |
          sdl-config --version
          cmake -D USE_SDL2_LIBS:BOOL=OFF ..
      - name: Configure
        if: matrix.sdl == 2
        working-directory: build
        run: |
          sdl2-config --version
          cmake -D USE_SDL2_LIBS:BOOL=ON -DUSE_PNG_SAVE=ON ..
      - name: Build
        working-directory: build
        run: make
  mingw-cross:
    runs-on: ubuntu-18.04
    env:
      SDL2DIR: /usr/
      CXX: i686-w64-mingw32-g++-posix
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y
          cmake
          g++-mingw-w64-i686
      - name: Install SDL2
        run: |
          curl -L https://github.com/mmatyas/supermariowar/releases/download/v2.0-beta.0/i686-w64-mingw32_mixerx.tar.xz | tar xJf - -C /tmp/
      - run: |
          $CXX --version
          cmake --version
          mkdir build
      - name: Configure
        working-directory: build
        run: cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../.travis/mingw_toolchain.cmake
          -DUSE_PNG_SAVE=ON
          -DUSE_SDL2_LIBS=ON
          -DSDL2_USE_MIXERX=ON
      - name: Build
        working-directory: build
        run: make
      - name: Package
        run: |
          mkdir deploy
          cp /usr/lib/gcc/i686-w64-mingw32/7.3-win32/{libgcc_s_sjlj-1,libstdc++-6}.dll deploy/
          cp /tmp/i686-w64-mingw32/usr/bin/{SDL2,SDL2_image,SDL2_mixer_ext}.dll deploy/
          cp build/Binaries/Release/{smw,smw-leveledit,smw-worldedit,smw-server}.exe deploy/
          i686-w64-mingw32-strip deploy/*
          cp docs/readme-v1.8.html deploy/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: smw_windows
          path: deploy
  android:
    if: false
    runs-on: ubuntu-18.04
    steps:
      - uses: android-actions/setup-android@v2
      - name: Install Android SDK
        run: sdkmanager "build-tools;23.0.1" "platforms;android-15"
      - name: Install Android NDK
        working-directory: /tmp
        run: |
          wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin;
          chmod +x ./android-ndk-r10e-linux-x86_64.bin;
          ./android-ndk-r10e-linux-x86_64.bin > /dev/null;
      - name: Install dependencies
        run: sudo dpkg --add-architecture i386 && sudo apt-get update -qq && sudo apt-get install -y
          ant
          expect
          lib32z1
          libbz2-1.0:i386
          libc6:i386
          libncurses5:i386
          libstdc++6:i386
          openjdk-8-jdk
      - name: Build
        run: |
          export PATH=$PATH:/tmp/android-ndk-r10e
          git clone --depth=1 https://github.com/mmatyas/supermariowar-android.git
          cd supermariowar-android
          git clone --depth=1 https://github.com/mmatyas/supermariowar.git
          ./build.sh --abi="armeabi-v7a arm64-v8a"
  emscripten:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Emscripten
        working-directory: /tmp
        run: |
          git clone https://github.com/emscripten-core/emsdk.git --depth=1
          cd emsdk
          ./emsdk install 1.39.5
          ./emsdk activate 1.39.5
      - name: Download SDL mixer
        working-directory: dependencies
        run: curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz | tar xzf -
      - name: Build
        run: |
          source /tmp/emsdk/emsdk_env.sh
          emcc -v
          sed -i 's|if (BUILD_STATIC_LIBS)|if (BUILD_STATIC_LIBS)\ninclude_directories(dependencies/SDL2_mixer-2.0.4)|' CMakeLists.txt
          mkdir build_js && cd build_js
          emconfigure cmake .. -DNO_NETWORK=1 -DDISABLE_SYSLIB_CHECKS=1 -DUSE_SDL2_LIBS=1
          emmake make smw
